server:
  port: 8094

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mscv_persona
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


